package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Advantisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.ad_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.ad_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.ad_show
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Boolean adShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.click_times
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer clickTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.end_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.release_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.simple_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String simpleDepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.url
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advantisement.detail_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String detailDepict;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.ad_id
     *
     * @return the value of advantisement.ad_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.ad_id
     *
     * @param adId the value for advantisement.ad_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.ad_name
     *
     * @return the value of advantisement.ad_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.ad_name
     *
     * @param adName the value for advantisement.ad_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.ad_show
     *
     * @return the value of advantisement.ad_show
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Boolean getAdShow() {
        return adShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.ad_show
     *
     * @param adShow the value for advantisement.ad_show
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAdShow(Boolean adShow) {
        this.adShow = adShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.build_time
     *
     * @return the value of advantisement.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.build_time
     *
     * @param buildTime the value for advantisement.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.click_times
     *
     * @return the value of advantisement.click_times
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getClickTimes() {
        return clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.click_times
     *
     * @param clickTimes the value for advantisement.click_times
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClickTimes(Integer clickTimes) {
        this.clickTimes = clickTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.end_time
     *
     * @return the value of advantisement.end_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.end_time
     *
     * @param endTime the value for advantisement.end_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.image
     *
     * @return the value of advantisement.image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.image
     *
     * @param image the value for advantisement.image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.release_time
     *
     * @return the value of advantisement.release_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.release_time
     *
     * @param releaseTime the value for advantisement.release_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.simple_depict
     *
     * @return the value of advantisement.simple_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSimpleDepict() {
        return simpleDepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.simple_depict
     *
     * @param simpleDepict the value for advantisement.simple_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSimpleDepict(String simpleDepict) {
        this.simpleDepict = simpleDepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.url
     *
     * @return the value of advantisement.url
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.url
     *
     * @param url the value for advantisement.url
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advantisement.detail_depict
     *
     * @return the value of advantisement.detail_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDetailDepict() {
        return detailDepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advantisement.detail_depict
     *
     * @param detailDepict the value for advantisement.detail_depict
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDetailDepict(String detailDepict) {
        this.detailDepict = detailDepict;
    }
}