package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.doctor_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.hospital_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.date
     *
     * @return the value of appointment.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.date
     *
     * @param date the value for appointment.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.doctor_name
     *
     * @return the value of appointment.doctor_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.doctor_name
     *
     * @param doctorName the value for appointment.doctor_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.hospital_name
     *
     * @return the value of appointment.hospital_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.hospital_name
     *
     * @param hospitalName the value for appointment.hospital_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.state
     *
     * @return the value of appointment.state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.state
     *
     * @param state the value for appointment.state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }
}