package com.mlnx.springmvc.mybatis.model;

public class AreaTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.area_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.area_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.one_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer oneLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.rank
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.three_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer threeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_table.two_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer twoLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.area_id
     *
     * @return the value of area_table.area_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.area_id
     *
     * @param areaId the value for area_table.area_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.area_name
     *
     * @return the value of area_table.area_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.area_name
     *
     * @param areaName the value for area_table.area_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.one_level
     *
     * @return the value of area_table.one_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getOneLevel() {
        return oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.one_level
     *
     * @param oneLevel the value for area_table.one_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOneLevel(Integer oneLevel) {
        this.oneLevel = oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.rank
     *
     * @return the value of area_table.rank
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.rank
     *
     * @param rank the value for area_table.rank
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.three_level
     *
     * @return the value of area_table.three_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getThreeLevel() {
        return threeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.three_level
     *
     * @param threeLevel the value for area_table.three_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setThreeLevel(Integer threeLevel) {
        this.threeLevel = threeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_table.two_level
     *
     * @return the value of area_table.two_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getTwoLevel() {
        return twoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_table.two_level
     *
     * @param twoLevel the value for area_table.two_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTwoLevel(Integer twoLevel) {
        this.twoLevel = twoLevel;
    }
}