package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.praise
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer praise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.collect
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer collect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer ccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.mark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.scount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer scount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.body
     *
     * @return the value of article.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.body
     *
     * @param body the value for article.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.author
     *
     * @return the value of article.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.author
     *
     * @param author the value for article.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.time
     *
     * @return the value of article.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.time
     *
     * @param time the value for article.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.type
     *
     * @return the value of article.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.type
     *
     * @param type the value for article.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.praise
     *
     * @return the value of article.praise
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.praise
     *
     * @param praise the value for article.praise
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.collect
     *
     * @return the value of article.collect
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCollect() {
        return collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.collect
     *
     * @param collect the value for article.collect
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCollect(Integer collect) {
        this.collect = collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.comment
     *
     * @return the value of article.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.comment
     *
     * @param comment the value for article.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ccount
     *
     * @return the value of article.ccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCcount() {
        return ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ccount
     *
     * @param ccount the value for article.ccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCcount(Integer ccount) {
        this.ccount = ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.date
     *
     * @return the value of article.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.date
     *
     * @param date the value for article.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.mark
     *
     * @return the value of article.mark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.mark
     *
     * @param mark the value for article.mark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.scount
     *
     * @return the value of article.scount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getScount() {
        return scount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.scount
     *
     * @param scount the value for article.scount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setScount(Integer scount) {
        this.scount = scount;
    }
}