package com.mlnx.springmvc.mybatis.model;

public class BookHomepageShowing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_homepage_showing.showing_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer showingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_homepage_showing.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_homepage_showing.showing_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String showingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_homepage_showing.showing_recoder
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer showingRecoder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_homepage_showing.showing_id
     *
     * @return the value of book_homepage_showing.showing_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getShowingId() {
        return showingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_homepage_showing.showing_id
     *
     * @param showingId the value for book_homepage_showing.showing_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setShowingId(Integer showingId) {
        this.showingId = showingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_homepage_showing.book_id
     *
     * @return the value of book_homepage_showing.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_homepage_showing.book_id
     *
     * @param bookId the value for book_homepage_showing.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_homepage_showing.showing_name
     *
     * @return the value of book_homepage_showing.showing_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getShowingName() {
        return showingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_homepage_showing.showing_name
     *
     * @param showingName the value for book_homepage_showing.showing_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setShowingName(String showingName) {
        this.showingName = showingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_homepage_showing.showing_recoder
     *
     * @return the value of book_homepage_showing.showing_recoder
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getShowingRecoder() {
        return showingRecoder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_homepage_showing.showing_recoder
     *
     * @param showingRecoder the value for book_homepage_showing.showing_recoder
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setShowingRecoder(Integer showingRecoder) {
        this.showingRecoder = showingRecoder;
    }
}