package com.mlnx.springmvc.mybatis.model;

public class BookClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.classification_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer classificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.class_first
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer classFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.class_second
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer classSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.class_third
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer classThird;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.classification_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String classificationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_classification.reorder_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer reorderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.classification_id
     *
     * @return the value of book_classification.classification_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getClassificationId() {
        return classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.classification_id
     *
     * @param classificationId the value for book_classification.classification_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClassificationId(Integer classificationId) {
        this.classificationId = classificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.class_first
     *
     * @return the value of book_classification.class_first
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getClassFirst() {
        return classFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.class_first
     *
     * @param classFirst the value for book_classification.class_first
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClassFirst(Integer classFirst) {
        this.classFirst = classFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.class_second
     *
     * @return the value of book_classification.class_second
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getClassSecond() {
        return classSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.class_second
     *
     * @param classSecond the value for book_classification.class_second
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClassSecond(Integer classSecond) {
        this.classSecond = classSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.class_third
     *
     * @return the value of book_classification.class_third
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getClassThird() {
        return classThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.class_third
     *
     * @param classThird the value for book_classification.class_third
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClassThird(Integer classThird) {
        this.classThird = classThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.classification_name
     *
     * @return the value of book_classification.classification_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getClassificationName() {
        return classificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.classification_name
     *
     * @param classificationName the value for book_classification.classification_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_classification.reorder_number
     *
     * @return the value of book_classification.reorder_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getReorderNumber() {
        return reorderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_classification.reorder_number
     *
     * @param reorderNumber the value for book_classification.reorder_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setReorderNumber(Integer reorderNumber) {
        this.reorderNumber = reorderNumber;
    }
}