package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class BookComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer commentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String commentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.cosumer_d
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.order_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.reply_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.comment_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String commentContains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.reply_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String replyContains;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_id
     *
     * @return the value of book_comment.comment_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_id
     *
     * @param commentId the value for book_comment.comment_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.book_id
     *
     * @return the value of book_comment.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.book_id
     *
     * @param bookId the value for book_comment.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_level
     *
     * @return the value of book_comment.comment_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCommentLevel() {
        return commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_level
     *
     * @param commentLevel the value for book_comment.comment_level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentLevel(Integer commentLevel) {
        this.commentLevel = commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_name
     *
     * @return the value of book_comment.comment_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCommentName() {
        return commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_name
     *
     * @param commentName the value for book_comment.comment_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentName(String commentName) {
        this.commentName = commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_time
     *
     * @return the value of book_comment.comment_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_time
     *
     * @param commentTime the value for book_comment.comment_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.cosumer_d
     *
     * @return the value of book_comment.cosumer_d
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerD() {
        return cosumerD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.cosumer_d
     *
     * @param cosumerD the value for book_comment.cosumer_d
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerD(Integer cosumerD) {
        this.cosumerD = cosumerD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.order_id
     *
     * @return the value of book_comment.order_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.order_id
     *
     * @param orderId the value for book_comment.order_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.reply_time
     *
     * @return the value of book_comment.reply_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.reply_time
     *
     * @param replyTime the value for book_comment.reply_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.comment_contains
     *
     * @return the value of book_comment.comment_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCommentContains() {
        return commentContains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.comment_contains
     *
     * @param commentContains the value for book_comment.comment_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentContains(String commentContains) {
        this.commentContains = commentContains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.reply_contains
     *
     * @return the value of book_comment.reply_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getReplyContains() {
        return replyContains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.reply_contains
     *
     * @param replyContains the value for book_comment.reply_contains
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setReplyContains(String replyContains) {
        this.replyContains = replyContains;
    }
}