package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_authorname
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookAuthorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_comments
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_pictures
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookPictures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_point
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_press
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookPress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_publish_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date bookPublishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double bookRetailprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_storeamont
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookStoreamont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.buyinglimiti_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer buyinglimitiAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.if_on_sale
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Boolean ifOnSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.on_sale_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date onSaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookDetails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_authorname
     *
     * @return the value of book.book_authorname
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookAuthorname() {
        return bookAuthorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_authorname
     *
     * @param bookAuthorname the value for book.book_authorname
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookAuthorname(String bookAuthorname) {
        this.bookAuthorname = bookAuthorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_comments
     *
     * @return the value of book.book_comments
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookComments() {
        return bookComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_comments
     *
     * @param bookComments the value for book.book_comments
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookComments(String bookComments) {
        this.bookComments = bookComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_pictures
     *
     * @return the value of book.book_pictures
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookPictures() {
        return bookPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_pictures
     *
     * @param bookPictures the value for book.book_pictures
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPictures(String bookPictures) {
        this.bookPictures = bookPictures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_point
     *
     * @return the value of book.book_point
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookPoint() {
        return bookPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_point
     *
     * @param bookPoint the value for book.book_point
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPoint(Integer bookPoint) {
        this.bookPoint = bookPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_press
     *
     * @return the value of book.book_press
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_press
     *
     * @param bookPress the value for book.book_press
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_price
     *
     * @return the value of book.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_price
     *
     * @param bookPrice the value for book.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPrice(Double bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_publish_time
     *
     * @return the value of book.book_publish_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getBookPublishTime() {
        return bookPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_publish_time
     *
     * @param bookPublishTime the value for book.book_publish_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPublishTime(Date bookPublishTime) {
        this.bookPublishTime = bookPublishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_retailprice
     *
     * @return the value of book.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getBookRetailprice() {
        return bookRetailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_retailprice
     *
     * @param bookRetailprice the value for book.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookRetailprice(Double bookRetailprice) {
        this.bookRetailprice = bookRetailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_storeamont
     *
     * @return the value of book.book_storeamont
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookStoreamont() {
        return bookStoreamont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_storeamont
     *
     * @param bookStoreamont the value for book.book_storeamont
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookStoreamont(Integer bookStoreamont) {
        this.bookStoreamont = bookStoreamont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.buyinglimiti_amount
     *
     * @return the value of book.buyinglimiti_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBuyinglimitiAmount() {
        return buyinglimitiAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.buyinglimiti_amount
     *
     * @param buyinglimitiAmount the value for book.buyinglimiti_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBuyinglimitiAmount(Integer buyinglimitiAmount) {
        this.buyinglimitiAmount = buyinglimitiAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.if_on_sale
     *
     * @return the value of book.if_on_sale
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Boolean getIfOnSale() {
        return ifOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.if_on_sale
     *
     * @param ifOnSale the value for book.if_on_sale
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIfOnSale(Boolean ifOnSale) {
        this.ifOnSale = ifOnSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.on_sale_time
     *
     * @return the value of book.on_sale_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getOnSaleTime() {
        return onSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.on_sale_time
     *
     * @param onSaleTime the value for book.on_sale_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOnSaleTime(Date onSaleTime) {
        this.onSaleTime = onSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_details
     *
     * @return the value of book.book_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookDetails() {
        return bookDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_details
     *
     * @param bookDetails the value for book.book_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookDetails(String bookDetails) {
        this.bookDetails = bookDetails;
    }
}