package com.mlnx.springmvc.mybatis.model;

public class CityHospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_hospital.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_hospital.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_hospital.id
     *
     * @return the value of city_hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_hospital.id
     *
     * @param id the value for city_hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_hospital.city_id
     *
     * @return the value of city_hospital.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_hospital.city_id
     *
     * @param cityId the value for city_hospital.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_hospital.hospital_id
     *
     * @return the value of city_hospital.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_hospital.hospital_id
     *
     * @param hospitalId the value for city_hospital.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }
}