package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.star
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.punctual
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer punctual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.attitude
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer attitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.title
     *
     * @return the value of comment.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.title
     *
     * @param title the value for comment.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.body
     *
     * @return the value of comment.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.body
     *
     * @param body the value for comment.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.star
     *
     * @return the value of comment.star
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.star
     *
     * @param star the value for comment.star
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.punctual
     *
     * @return the value of comment.punctual
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getPunctual() {
        return punctual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.punctual
     *
     * @param punctual the value for comment.punctual
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPunctual(Integer punctual) {
        this.punctual = punctual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.attitude
     *
     * @return the value of comment.attitude
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getAttitude() {
        return attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.attitude
     *
     * @param attitude the value for comment.attitude
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAttitude(Integer attitude) {
        this.attitude = attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.skill
     *
     * @return the value of comment.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.skill
     *
     * @param skill the value for comment.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSkill(Integer skill) {
        this.skill = skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}