package com.mlnx.springmvc.mybatis.model;

public class Cosumer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String cosumerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_condition
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Short cosumerCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_headpicture
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String cosumerHeadpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String cosumerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String cosumerPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_phonenumber
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerPhonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Short cosumerSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.cosumer_zipcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cosumer.mai_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String maiAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_id
     *
     * @return the value of cosumer.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerId() {
        return cosumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_id
     *
     * @param cosumerId the value for cosumer.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerId(Integer cosumerId) {
        this.cosumerId = cosumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_address
     *
     * @return the value of cosumer.cosumer_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCosumerAddress() {
        return cosumerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_address
     *
     * @param cosumerAddress the value for cosumer.cosumer_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerAddress(String cosumerAddress) {
        this.cosumerAddress = cosumerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_condition
     *
     * @return the value of cosumer.cosumer_condition
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Short getCosumerCondition() {
        return cosumerCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_condition
     *
     * @param cosumerCondition the value for cosumer.cosumer_condition
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerCondition(Short cosumerCondition) {
        this.cosumerCondition = cosumerCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_headpicture
     *
     * @return the value of cosumer.cosumer_headpicture
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCosumerHeadpicture() {
        return cosumerHeadpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_headpicture
     *
     * @param cosumerHeadpicture the value for cosumer.cosumer_headpicture
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerHeadpicture(String cosumerHeadpicture) {
        this.cosumerHeadpicture = cosumerHeadpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_name
     *
     * @return the value of cosumer.cosumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCosumerName() {
        return cosumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_name
     *
     * @param cosumerName the value for cosumer.cosumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerName(String cosumerName) {
        this.cosumerName = cosumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_password
     *
     * @return the value of cosumer.cosumer_password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCosumerPassword() {
        return cosumerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_password
     *
     * @param cosumerPassword the value for cosumer.cosumer_password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerPassword(String cosumerPassword) {
        this.cosumerPassword = cosumerPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_phonenumber
     *
     * @return the value of cosumer.cosumer_phonenumber
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerPhonenumber() {
        return cosumerPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_phonenumber
     *
     * @param cosumerPhonenumber the value for cosumer.cosumer_phonenumber
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerPhonenumber(Integer cosumerPhonenumber) {
        this.cosumerPhonenumber = cosumerPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_points
     *
     * @return the value of cosumer.cosumer_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerPoints() {
        return cosumerPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_points
     *
     * @param cosumerPoints the value for cosumer.cosumer_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerPoints(Integer cosumerPoints) {
        this.cosumerPoints = cosumerPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_sex
     *
     * @return the value of cosumer.cosumer_sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Short getCosumerSex() {
        return cosumerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_sex
     *
     * @param cosumerSex the value for cosumer.cosumer_sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerSex(Short cosumerSex) {
        this.cosumerSex = cosumerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.cosumer_zipcode
     *
     * @return the value of cosumer.cosumer_zipcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerZipcode() {
        return cosumerZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.cosumer_zipcode
     *
     * @param cosumerZipcode the value for cosumer.cosumer_zipcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerZipcode(Integer cosumerZipcode) {
        this.cosumerZipcode = cosumerZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cosumer.mai_address
     *
     * @return the value of cosumer.mai_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getMaiAddress() {
        return maiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cosumer.mai_address
     *
     * @param maiAddress the value for cosumer.mai_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setMaiAddress(String maiAddress) {
        this.maiAddress = maiAddress;
    }
}