package com.mlnx.springmvc.mybatis.model;

public class DeliveryAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.delivery_address_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer deliveryAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.acquiesce
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Boolean acquiesce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.city_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.connect_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer connectNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.detail_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.district_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.district_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.province_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.delivery_address_id
     *
     * @return the value of delivery_address.delivery_address_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDeliveryAddressId() {
        return deliveryAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.delivery_address_id
     *
     * @param deliveryAddressId the value for delivery_address.delivery_address_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDeliveryAddressId(Integer deliveryAddressId) {
        this.deliveryAddressId = deliveryAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.acquiesce
     *
     * @return the value of delivery_address.acquiesce
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Boolean getAcquiesce() {
        return acquiesce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.acquiesce
     *
     * @param acquiesce the value for delivery_address.acquiesce
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAcquiesce(Boolean acquiesce) {
        this.acquiesce = acquiesce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.city_id
     *
     * @return the value of delivery_address.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.city_id
     *
     * @param cityId the value for delivery_address.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.city_name
     *
     * @return the value of delivery_address.city_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.city_name
     *
     * @param cityName the value for delivery_address.city_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.connect_number
     *
     * @return the value of delivery_address.connect_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getConnectNumber() {
        return connectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.connect_number
     *
     * @param connectNumber the value for delivery_address.connect_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConnectNumber(Integer connectNumber) {
        this.connectNumber = connectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.consignee_name
     *
     * @return the value of delivery_address.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.consignee_name
     *
     * @param consigneeName the value for delivery_address.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.detail_address
     *
     * @return the value of delivery_address.detail_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.detail_address
     *
     * @param detailAddress the value for delivery_address.detail_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.district_id
     *
     * @return the value of delivery_address.district_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.district_id
     *
     * @param districtId the value for delivery_address.district_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.district_name
     *
     * @return the value of delivery_address.district_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.district_name
     *
     * @param districtName the value for delivery_address.district_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.postcode
     *
     * @return the value of delivery_address.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.postcode
     *
     * @param postcode the value for delivery_address.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPostcode(Integer postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.province_id
     *
     * @return the value of delivery_address.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.province_id
     *
     * @param provinceId the value for delivery_address.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.province_name
     *
     * @return the value of delivery_address.province_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.province_name
     *
     * @param provinceName the value for delivery_address.province_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.user_id
     *
     * @return the value of delivery_address.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.user_id
     *
     * @param userId the value for delivery_address.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}