package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer office;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.order_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.consult
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer consult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.group_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.commentlist
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer commentlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.achievement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String achievement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.background
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String background;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.birthday
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.phone
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.province
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.voipAccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String voipaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.voipPassword
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String voippassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.id
     *
     * @return the value of doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.id
     *
     * @param id the value for doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.name
     *
     * @return the value of doctor.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.name
     *
     * @param name the value for doctor.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.office
     *
     * @return the value of doctor.office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.office
     *
     * @param office the value for doctor.office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOffice(Integer office) {
        this.office = office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.title
     *
     * @return the value of doctor.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.title
     *
     * @param title the value for doctor.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.hospital
     *
     * @return the value of doctor.hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.hospital
     *
     * @param hospital the value for doctor.hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHospital(Integer hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.order_
     *
     * @return the value of doctor.order_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.order_
     *
     * @param order the value for doctor.order_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.consult
     *
     * @return the value of doctor.consult
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getConsult() {
        return consult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.consult
     *
     * @param consult the value for doctor.consult
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConsult(Integer consult) {
        this.consult = consult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.group_
     *
     * @return the value of doctor.group_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.group_
     *
     * @param group the value for doctor.group_
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGroup(Integer group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.skill
     *
     * @return the value of doctor.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.skill
     *
     * @param skill the value for doctor.skill
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSkill(String skill) {
        this.skill = skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.comment
     *
     * @return the value of doctor.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.comment
     *
     * @param comment the value for doctor.comment
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.commentlist
     *
     * @return the value of doctor.commentlist
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCommentlist() {
        return commentlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.commentlist
     *
     * @param commentlist the value for doctor.commentlist
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCommentlist(Integer commentlist) {
        this.commentlist = commentlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.achievement
     *
     * @return the value of doctor.achievement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getAchievement() {
        return achievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.achievement
     *
     * @param achievement the value for doctor.achievement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAchievement(String achievement) {
        this.achievement = achievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.background
     *
     * @return the value of doctor.background
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBackground() {
        return background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.background
     *
     * @param background the value for doctor.background
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBackground(String background) {
        this.background = background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.birthday
     *
     * @return the value of doctor.birthday
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.birthday
     *
     * @param birthday the value for doctor.birthday
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.city
     *
     * @return the value of doctor.city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.city
     *
     * @param city the value for doctor.city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.date
     *
     * @return the value of doctor.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.date
     *
     * @param date the value for doctor.date
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.password
     *
     * @return the value of doctor.password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.password
     *
     * @param password the value for doctor.password
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.phone
     *
     * @return the value of doctor.phone
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.phone
     *
     * @param phone the value for doctor.phone
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.pic
     *
     * @return the value of doctor.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.pic
     *
     * @param pic the value for doctor.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.province
     *
     * @return the value of doctor.province
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.province
     *
     * @param province the value for doctor.province
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.sex
     *
     * @return the value of doctor.sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.sex
     *
     * @param sex the value for doctor.sex
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.voipAccount
     *
     * @return the value of doctor.voipAccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getVoipaccount() {
        return voipaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.voipAccount
     *
     * @param voipaccount the value for doctor.voipAccount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setVoipaccount(String voipaccount) {
        this.voipaccount = voipaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.voipPassword
     *
     * @return the value of doctor.voipPassword
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getVoippassword() {
        return voippassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.voipPassword
     *
     * @param voippassword the value for doctor.voipPassword
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setVoippassword(String voippassword) {
        this.voippassword = voippassword;
    }
}