package com.mlnx.springmvc.mybatis.model;

public class DoctorDoctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_doctor.friend_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_doctor.id
     *
     * @return the value of doctor_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_doctor.id
     *
     * @param id the value for doctor_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_doctor.doctor_id
     *
     * @return the value of doctor_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_doctor.doctor_id
     *
     * @param doctorId the value for doctor_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_doctor.friend_id
     *
     * @return the value of doctor_doctor.friend_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_doctor.friend_id
     *
     * @param friendId the value for doctor_doctor.friend_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }
}