package com.mlnx.springmvc.mybatis.model;

public class DoctorGroupa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_groupa.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_groupa.group_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_groupa.id
     *
     * @return the value of doctor_groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_groupa.id
     *
     * @param id the value for doctor_groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_groupa.doctor_id
     *
     * @return the value of doctor_groupa.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_groupa.doctor_id
     *
     * @param doctorId the value for doctor_groupa.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_groupa.group_id
     *
     * @return the value of doctor_groupa.group_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_groupa.group_id
     *
     * @param groupId the value for doctor_groupa.group_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}