package com.mlnx.springmvc.mybatis.model;

public class Groupa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupa.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupa.count
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupa.description
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupa.id
     *
     * @return the value of groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupa.id
     *
     * @param id the value for groupa.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupa.name
     *
     * @return the value of groupa.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupa.name
     *
     * @param name the value for groupa.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupa.count
     *
     * @return the value of groupa.count
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupa.count
     *
     * @param count the value for groupa.count
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupa.description
     *
     * @return the value of groupa.description
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupa.description
     *
     * @param description the value for groupa.description
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}