package com.mlnx.springmvc.mybatis.model;

public class HibernateSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hibernate_sequence.next_val
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Long nextVal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hibernate_sequence.next_val
     *
     * @return the value of hibernate_sequence.next_val
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Long getNextVal() {
        return nextVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hibernate_sequence.next_val
     *
     * @param nextVal the value for hibernate_sequence.next_val
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setNextVal(Long nextVal) {
        this.nextVal = nextVal;
    }
}