package com.mlnx.springmvc.mybatis.model;

public class HospitalDoctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.id
     *
     * @return the value of hospital_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.id
     *
     * @param id the value for hospital_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.hospital_id
     *
     * @return the value of hospital_doctor.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.hospital_id
     *
     * @param hospitalId the value for hospital_doctor.hospital_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_doctor.doctor_id
     *
     * @return the value of hospital_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_doctor.doctor_id
     *
     * @param doctorId the value for hospital_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
}