package com.mlnx.springmvc.mybatis.model;

public class Hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.id
     *
     * @return the value of hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.id
     *
     * @param id the value for hospital.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.name
     *
     * @return the value of hospital.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.name
     *
     * @param name the value for hospital.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}