package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Indent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer indentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.consumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String consumerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.contact_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer contactNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.deliver_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String deliverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date indentBuildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_oldprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double indentOldprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_payment_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Short indentPaymentWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_payprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double indentPayprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Short indentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.logistic_fee
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double logisticFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.logistic_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer logisticNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.logistic_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String logisticWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.consumer_remark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String consumerRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_id
     *
     * @return the value of indent.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getIndentId() {
        return indentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_id
     *
     * @param indentId the value for indent.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentId(Integer indentId) {
        this.indentId = indentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.consignee_name
     *
     * @return the value of indent.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.consignee_name
     *
     * @param consigneeName the value for indent.consignee_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.consumer_name
     *
     * @return the value of indent.consumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.consumer_name
     *
     * @param consumerName the value for indent.consumer_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConsumerName(String consumerName) {
        this.consumerName = consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.contact_number
     *
     * @return the value of indent.contact_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.contact_number
     *
     * @param contactNumber the value for indent.contact_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setContactNumber(Integer contactNumber) {
        this.contactNumber = contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.deliver_address
     *
     * @return the value of indent.deliver_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getDeliverAddress() {
        return deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.deliver_address
     *
     * @param deliverAddress the value for indent.deliver_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDeliverAddress(String deliverAddress) {
        this.deliverAddress = deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_build_time
     *
     * @return the value of indent.indent_build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getIndentBuildTime() {
        return indentBuildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_build_time
     *
     * @param indentBuildTime the value for indent.indent_build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentBuildTime(Date indentBuildTime) {
        this.indentBuildTime = indentBuildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_oldprice
     *
     * @return the value of indent.indent_oldprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getIndentOldprice() {
        return indentOldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_oldprice
     *
     * @param indentOldprice the value for indent.indent_oldprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentOldprice(Double indentOldprice) {
        this.indentOldprice = indentOldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_payment_way
     *
     * @return the value of indent.indent_payment_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Short getIndentPaymentWay() {
        return indentPaymentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_payment_way
     *
     * @param indentPaymentWay the value for indent.indent_payment_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentPaymentWay(Short indentPaymentWay) {
        this.indentPaymentWay = indentPaymentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_payprice
     *
     * @return the value of indent.indent_payprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getIndentPayprice() {
        return indentPayprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_payprice
     *
     * @param indentPayprice the value for indent.indent_payprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentPayprice(Double indentPayprice) {
        this.indentPayprice = indentPayprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_state
     *
     * @return the value of indent.indent_state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Short getIndentState() {
        return indentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_state
     *
     * @param indentState the value for indent.indent_state
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentState(Short indentState) {
        this.indentState = indentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.logistic_fee
     *
     * @return the value of indent.logistic_fee
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getLogisticFee() {
        return logisticFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.logistic_fee
     *
     * @param logisticFee the value for indent.logistic_fee
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLogisticFee(Double logisticFee) {
        this.logisticFee = logisticFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.logistic_number
     *
     * @return the value of indent.logistic_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getLogisticNumber() {
        return logisticNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.logistic_number
     *
     * @param logisticNumber the value for indent.logistic_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLogisticNumber(Integer logisticNumber) {
        this.logisticNumber = logisticNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.logistic_way
     *
     * @return the value of indent.logistic_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getLogisticWay() {
        return logisticWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.logistic_way
     *
     * @param logisticWay the value for indent.logistic_way
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLogisticWay(String logisticWay) {
        this.logisticWay = logisticWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.postcode
     *
     * @return the value of indent.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.postcode
     *
     * @param postcode the value for indent.postcode
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPostcode(Integer postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_id
     *
     * @return the value of indent.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_id
     *
     * @param userId the value for indent.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.consumer_remark
     *
     * @return the value of indent.consumer_remark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getConsumerRemark() {
        return consumerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.consumer_remark
     *
     * @param consumerRemark the value for indent.consumer_remark
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setConsumerRemark(String consumerRemark) {
        this.consumerRemark = consumerRemark;
    }
}