package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class IndentDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.goods_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer goodsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.goods_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.goods_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String goodsImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.goods_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.goods_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent_details.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer indentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.id
     *
     * @return the value of indent_details.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.id
     *
     * @param id the value for indent_details.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.build_time
     *
     * @return the value of indent_details.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.build_time
     *
     * @param buildTime the value for indent_details.build_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBuildTime(Date buildTime) {
        this.buildTime = buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.goods_amount
     *
     * @return the value of indent_details.goods_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.goods_amount
     *
     * @param goodsAmount the value for indent_details.goods_amount
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGoodsAmount(Integer goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.goods_id
     *
     * @return the value of indent_details.goods_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.goods_id
     *
     * @param goodsId the value for indent_details.goods_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.goods_image
     *
     * @return the value of indent_details.goods_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getGoodsImage() {
        return goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.goods_image
     *
     * @param goodsImage the value for indent_details.goods_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGoodsImage(String goodsImage) {
        this.goodsImage = goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.goods_name
     *
     * @return the value of indent_details.goods_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.goods_name
     *
     * @param goodsName the value for indent_details.goods_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.goods_price
     *
     * @return the value of indent_details.goods_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.goods_price
     *
     * @param goodsPrice the value for indent_details.goods_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent_details.indent_id
     *
     * @return the value of indent_details.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getIndentId() {
        return indentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent_details.indent_id
     *
     * @param indentId the value for indent_details.indent_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setIndentId(Integer indentId) {
        this.indentId = indentId;
    }
}