package com.mlnx.springmvc.mybatis.model;

public class Manager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_code
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String managerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String managerImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String managerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.stop_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Boolean stopAdministrator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.super_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Boolean superAdministrator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_code
     *
     * @return the value of manager.manager_code
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getManagerCode() {
        return managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_code
     *
     * @param managerCode the value for manager.manager_code
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setManagerCode(String managerCode) {
        this.managerCode = managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_image
     *
     * @return the value of manager.manager_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getManagerImage() {
        return managerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_image
     *
     * @param managerImage the value for manager.manager_image
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setManagerImage(String managerImage) {
        this.managerImage = managerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_number
     *
     * @return the value of manager.manager_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getManagerNumber() {
        return managerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_number
     *
     * @param managerNumber the value for manager.manager_number
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setManagerNumber(String managerNumber) {
        this.managerNumber = managerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.stop_administrator
     *
     * @return the value of manager.stop_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Boolean getStopAdministrator() {
        return stopAdministrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.stop_administrator
     *
     * @param stopAdministrator the value for manager.stop_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setStopAdministrator(Boolean stopAdministrator) {
        this.stopAdministrator = stopAdministrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.super_administrator
     *
     * @return the value of manager.super_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Boolean getSuperAdministrator() {
        return superAdministrator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.super_administrator
     *
     * @param superAdministrator the value for manager.super_administrator
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSuperAdministrator(Boolean superAdministrator) {
        this.superAdministrator = superAdministrator;
    }
}