package com.mlnx.springmvc.mybatis.model;

public class OfficeDoctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_doctor.office_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer officeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column office_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer doctorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_doctor.id
     *
     * @return the value of office_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_doctor.id
     *
     * @param id the value for office_doctor.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_doctor.office_id
     *
     * @return the value of office_doctor.office_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getOfficeId() {
        return officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_doctor.office_id
     *
     * @param officeId the value for office_doctor.office_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column office_doctor.doctor_id
     *
     * @return the value of office_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column office_doctor.doctor_id
     *
     * @param doctorId the value for office_doctor.doctor_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }
}