package com.mlnx.springmvc.mybatis.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owner
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.specifications
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.body
     *
     * @return the value of product.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.body
     *
     * @param body the value for product.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.owner
     *
     * @return the value of product.owner
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.owner
     *
     * @param owner the value for product.owner
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pic
     *
     * @return the value of product.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pic
     *
     * @param pic the value for product.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.specifications
     *
     * @return the value of product.specifications
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.specifications
     *
     * @param specifications the value for product.specifications
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }
}