package com.mlnx.springmvc.mybatis.model;

public class ProvinceCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province_city.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province_city.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province_city.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer provinceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province_city.id
     *
     * @return the value of province_city.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province_city.id
     *
     * @param id the value for province_city.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province_city.city_id
     *
     * @return the value of province_city.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province_city.city_id
     *
     * @param cityId the value for province_city.city_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province_city.province_id
     *
     * @return the value of province_city.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province_city.province_id
     *
     * @param provinceId the value for province_city.province_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
}