package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String suggest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.title
     *
     * @return the value of report.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.title
     *
     * @param title the value for report.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.body
     *
     * @return the value of report.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.body
     *
     * @param body the value for report.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.author
     *
     * @return the value of report.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.author
     *
     * @param author the value for report.author
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.time
     *
     * @return the value of report.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.time
     *
     * @param time the value for report.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.suggest
     *
     * @return the value of report.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.suggest
     *
     * @param suggest the value for report.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }
}