package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class Shoppingcart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.shoppingcart_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer shoppingcartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.addingcart_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date addingcartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_amout
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookAmout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer bookPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Double bookRetailprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer cosumerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.shoppingcart_id
     *
     * @return the value of shoppingcart.shoppingcart_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getShoppingcartId() {
        return shoppingcartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.shoppingcart_id
     *
     * @param shoppingcartId the value for shoppingcart.shoppingcart_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setShoppingcartId(Integer shoppingcartId) {
        this.shoppingcartId = shoppingcartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.addingcart_time
     *
     * @return the value of shoppingcart.addingcart_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getAddingcartTime() {
        return addingcartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.addingcart_time
     *
     * @param addingcartTime the value for shoppingcart.addingcart_time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAddingcartTime(Date addingcartTime) {
        this.addingcartTime = addingcartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_amout
     *
     * @return the value of shoppingcart.book_amout
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookAmout() {
        return bookAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_amout
     *
     * @param bookAmout the value for shoppingcart.book_amout
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookAmout(Integer bookAmout) {
        this.bookAmout = bookAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_id
     *
     * @return the value of shoppingcart.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_id
     *
     * @param bookId the value for shoppingcart.book_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_name
     *
     * @return the value of shoppingcart.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_name
     *
     * @param bookName the value for shoppingcart.book_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_points
     *
     * @return the value of shoppingcart.book_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getBookPoints() {
        return bookPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_points
     *
     * @param bookPoints the value for shoppingcart.book_points
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPoints(Integer bookPoints) {
        this.bookPoints = bookPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_price
     *
     * @return the value of shoppingcart.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_price
     *
     * @param bookPrice the value for shoppingcart.book_price
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookPrice(Double bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.book_retailprice
     *
     * @return the value of shoppingcart.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Double getBookRetailprice() {
        return bookRetailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.book_retailprice
     *
     * @param bookRetailprice the value for shoppingcart.book_retailprice
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBookRetailprice(Double bookRetailprice) {
        this.bookRetailprice = bookRetailprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cosumer_id
     *
     * @return the value of shoppingcart.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getCosumerId() {
        return cosumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cosumer_id
     *
     * @param cosumerId the value for shoppingcart.cosumer_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setCosumerId(Integer cosumerId) {
        this.cosumerId = cosumerId;
    }
}