package com.mlnx.springmvc.mybatis.model;

public class TBloodPressureSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_pressure_setting.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_pressure_setting.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_pressure_setting.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_pressure_setting.periodic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer periodic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_pressure_setting.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure_setting.id
     *
     * @return the value of t_blood_pressure_setting.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure_setting.id
     *
     * @param id the value for t_blood_pressure_setting.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure_setting.high
     *
     * @return the value of t_blood_pressure_setting.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure_setting.high
     *
     * @param high the value for t_blood_pressure_setting.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHigh(Integer high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure_setting.low
     *
     * @return the value of t_blood_pressure_setting.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure_setting.low
     *
     * @param low the value for t_blood_pressure_setting.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLow(Integer low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure_setting.periodic
     *
     * @return the value of t_blood_pressure_setting.periodic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getPeriodic() {
        return periodic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure_setting.periodic
     *
     * @param periodic the value for t_blood_pressure_setting.periodic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPeriodic(Integer periodic) {
        this.periodic = periodic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_pressure_setting.user_id
     *
     * @return the value of t_blood_pressure_setting.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_pressure_setting.user_id
     *
     * @param userId the value for t_blood_pressure_setting.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}