package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class TBloodSugarCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.normal
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer normal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.total
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blood_sugar_collection.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.id
     *
     * @return the value of t_blood_sugar_collection.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.id
     *
     * @param id the value for t_blood_sugar_collection.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.high
     *
     * @return the value of t_blood_sugar_collection.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.high
     *
     * @param high the value for t_blood_sugar_collection.high
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setHigh(Integer high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.low
     *
     * @return the value of t_blood_sugar_collection.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.low
     *
     * @param low the value for t_blood_sugar_collection.low
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLow(Integer low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.normal
     *
     * @return the value of t_blood_sugar_collection.normal
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getNormal() {
        return normal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.normal
     *
     * @param normal the value for t_blood_sugar_collection.normal
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setNormal(Integer normal) {
        this.normal = normal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.total
     *
     * @return the value of t_blood_sugar_collection.total
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.total
     *
     * @param total the value for t_blood_sugar_collection.total
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.time
     *
     * @return the value of t_blood_sugar_collection.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.time
     *
     * @param time the value for t_blood_sugar_collection.time
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blood_sugar_collection.user_id
     *
     * @return the value of t_blood_sugar_collection.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blood_sugar_collection.user_id
     *
     * @param userId the value for t_blood_sugar_collection.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}