package com.mlnx.springmvc.mybatis.model;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String testName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_id
     *
     * @return the value of test.test_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_id
     *
     * @param testId the value for test.test_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_name
     *
     * @return the value of test.test_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_name
     *
     * @param testName the value for test.test_name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTestName(String testName) {
        this.testName = testName;
    }
}