package com.mlnx.springmvc.mybatis.model;

import java.util.Date;

public class TPhoneValid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phone_valid.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phone_valid.phone
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phone_valid.validcode
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer validcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_phone_valid.date
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phone_valid.id
     *
     * @return the value of t_phone_valid.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phone_valid.id
     *
     * @param id the value for t_phone_valid.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phone_valid.phone
     *
     * @return the value of t_phone_valid.phone
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phone_valid.phone
     *
     * @param phone the value for t_phone_valid.phone
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phone_valid.validcode
     *
     * @return the value of t_phone_valid.validcode
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getValidcode() {
        return validcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phone_valid.validcode
     *
     * @param validcode the value for t_phone_valid.validcode
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setValidcode(Integer validcode) {
        this.validcode = validcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_phone_valid.date
     *
     * @return the value of t_phone_valid.date
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_phone_valid.date
     *
     * @param date the value for t_phone_valid.date
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }
}