package com.mlnx.springmvc.mybatis.model;

public class TReportContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String suggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.proportion
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer proportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_report_content.score
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.id
     *
     * @return the value of t_report_content.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.id
     *
     * @param id the value for t_report_content.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.title
     *
     * @return the value of t_report_content.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.title
     *
     * @param title the value for t_report_content.title
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.body
     *
     * @return the value of t_report_content.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.body
     *
     * @param body the value for t_report_content.body
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.suggest
     *
     * @return the value of t_report_content.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.suggest
     *
     * @param suggest the value for t_report_content.suggest
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.level
     *
     * @return the value of t_report_content.level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.level
     *
     * @param level the value for t_report_content.level
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.proportion
     *
     * @return the value of t_report_content.proportion
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getProportion() {
        return proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.proportion
     *
     * @param proportion the value for t_report_content.proportion
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setProportion(Integer proportion) {
        this.proportion = proportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_report_content.score
     *
     * @return the value of t_report_content.score
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_report_content.score
     *
     * @param score the value for t_report_content.score
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}