package com.mlnx.springmvc.mybatis.model;

public class TUserFriends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.user_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.friend_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.group_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.fouce
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer fouce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.open
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private Integer open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_friends.remark
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.id
     *
     * @return the value of t_user_friends.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.id
     *
     * @param id the value for t_user_friends.id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.user_id
     *
     * @return the value of t_user_friends.user_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.user_id
     *
     * @param userId the value for t_user_friends.user_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.friend_id
     *
     * @return the value of t_user_friends.friend_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.friend_id
     *
     * @param friendId the value for t_user_friends.friend_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.group_id
     *
     * @return the value of t_user_friends.group_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.group_id
     *
     * @param groupId the value for t_user_friends.group_id
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.fouce
     *
     * @return the value of t_user_friends.fouce
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getFouce() {
        return fouce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.fouce
     *
     * @param fouce the value for t_user_friends.fouce
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setFouce(Integer fouce) {
        this.fouce = fouce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.open
     *
     * @return the value of t_user_friends.open
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.open
     *
     * @param open the value for t_user_friends.open
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_friends.remark
     *
     * @return the value of t_user_friends.remark
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_friends.remark
     *
     * @param remark the value for t_user_friends.remark
     *
     * @mbggenerated Thu Nov 12 15:45:41 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}