package com.mlnx.springmvc.mybatis.model;

public class TUserExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.age
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_ext.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.id
     *
     * @return the value of t_user_ext.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.id
     *
     * @param id the value for t_user_ext.id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.name
     *
     * @return the value of t_user_ext.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.name
     *
     * @param name the value for t_user_ext.name
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.age
     *
     * @return the value of t_user_ext.age
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.age
     *
     * @param age the value for t_user_ext.age
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.pic
     *
     * @return the value of t_user_ext.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.pic
     *
     * @param pic the value for t_user_ext.pic
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_ext.user_id
     *
     * @return the value of t_user_ext.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_ext.user_id
     *
     * @param userId the value for t_user_ext.user_id
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}