package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Advantisement;
import java.util.List;

public interface AdvantisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advantisement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advantisement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Advantisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advantisement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Advantisement selectByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advantisement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Advantisement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advantisement
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Advantisement record);
}