package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.AreaTable;
import java.util.List;

public interface AreaTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_table
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_table
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(AreaTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_table
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    AreaTable selectByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_table
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<AreaTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_table
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(AreaTable record);
}