package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.BookHomepageShowing;
import java.util.List;

public interface BookHomepageShowingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_homepage_showing
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer showingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_homepage_showing
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(BookHomepageShowing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_homepage_showing
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    BookHomepageShowing selectByPrimaryKey(Integer showingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_homepage_showing
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<BookHomepageShowing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_homepage_showing
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(BookHomepageShowing record);
}