package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.BookClassification;
import java.util.List;

public interface BookClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classification
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer classificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classification
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(BookClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classification
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    BookClassification selectByPrimaryKey(Integer classificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classification
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<BookClassification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classification
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(BookClassification record);
}