package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.CityHospital;
import java.util.List;

public interface CityHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(CityHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    CityHospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<CityHospital> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_hospital
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(CityHospital record);
}