package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Cosumer;
import java.util.List;

public interface CosumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cosumer
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer cosumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cosumer
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Cosumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cosumer
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Cosumer selectByPrimaryKey(Integer cosumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cosumer
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Cosumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cosumer
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Cosumer record);
}