package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.DeliveryAddress;
import java.util.List;

public interface DeliveryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer deliveryAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(DeliveryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    DeliveryAddress selectByPrimaryKey(Integer deliveryAddressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<DeliveryAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_address
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(DeliveryAddress record);
}