package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.DoctorDoctor;
import java.util.List;

public interface DoctorDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(DoctorDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    DoctorDoctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<DoctorDoctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(DoctorDoctor record);
}