package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.DoctorGroupa;
import java.util.List;

public interface DoctorGroupaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(DoctorGroupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    DoctorGroupa selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<DoctorGroupa> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(DoctorGroupa record);
}