package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Groupa;
import java.util.List;

public interface GroupaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Groupa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Groupa selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Groupa> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupa
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Groupa record);
}