package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.HospitalDoctor;
import java.util.List;

public interface HospitalDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(HospitalDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    HospitalDoctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<HospitalDoctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_doctor
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(HospitalDoctor record);
}