package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Indent;
import java.util.List;

public interface IndentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer indentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Indent selectByPrimaryKey(Integer indentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Indent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Indent record);
}