package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.IndentDetails;
import java.util.List;

public interface IndentDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(IndentDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    IndentDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<IndentDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent_details
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(IndentDetails record);
}