package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Office;
import java.util.List;

public interface OfficeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Office record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Office selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Office> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table office
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Office record);
}