package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.ProvinceCity;
import java.util.List;

public interface ProvinceCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province_city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province_city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(ProvinceCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province_city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    ProvinceCity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province_city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<ProvinceCity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province_city
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(ProvinceCity record);
}