package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.Shoppingcart;
import java.util.List;

public interface ShoppingcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer shoppingcartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    Shoppingcart selectByPrimaryKey(Integer shoppingcartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<Shoppingcart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcart
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(Shoppingcart record);
}