package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.TBloodPressureSetting;
import java.util.List;

public interface TBloodPressureSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TBloodPressureSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TBloodPressureSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TBloodPressureSetting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_setting
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TBloodPressureSetting record);
}