package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.TBloodPressureCollection;
import java.util.List;

public interface TBloodPressureCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_collection
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_collection
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TBloodPressureCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_collection
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TBloodPressureCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_collection
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TBloodPressureCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blood_pressure_collection
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TBloodPressureCollection record);
}