package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.TReportContent;
import java.util.List;

public interface TReportContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TReportContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TReportContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TReportContent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report_content
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TReportContent record);
}