package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.TReport;
import java.util.List;

public interface TReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TReport record);
}