package com.mlnx.springmvc.mybatis.mapper;

import com.mlnx.springmvc.mybatis.model.TUserExt;
import java.util.List;

public interface TUserExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int insert(TUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    TUserExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    List<TUserExt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ext
     *
     * @mbggenerated Fri Nov 06 10:14:27 CST 2015
     */
    int updateByPrimaryKey(TUserExt record);
}